### ISSUE TITLE
Can't Specify Custom Deployment Bucket

### ISSUE THREAD

**Issue by brettneese** [dougmoscrop/serverless-plugin-split-stacks#6] opened 2017-08-10 18:56 UTC
When I specify a custom deployment bucket in `provider.deploymentBucket`; ie:

```
provider:
  deploymentBucket:
    name: $bucket
    serverSideEncryption: AES256 
```

I get:

```
The CloudFormation template is invalid: Template format error: Unresolved resource dependencies [ServerlessDeploymentBucket] in the Resources block of the template
```

The easiest solution to this problem is to simply remove the `provider.deploymentBucket` property and use whatever the Serverless framework gives you, however, it would be nice if this plugin did not have this issue.

That being said, I don't understand any of the magic going on here, so that solution is good enough for us for now.

**Comment by ghostrocket** [comment] 2017-10-07 16:14
just got this too. workaround was to remove bucket

**Comment by dougmoscrop** [comment] 2017-10-07 19:15
Fixed via 1.2.1, let me know if it does not work for you!

**Closed by dougmoscrop** 2017-10-07 19:15 UTC

**Comment by ghostrocket** [comment] 2017-10-08 18:06
thank you @dougmoscrop!

**Comment by rafaelrpinto** [comment] 2019-02-06 14:12
@dougmoscrop 
I'm facing this issue on `^1.7.0` only on ymls that also declare resources. The ones without resources declared work fine.

**Comment by rafaelrpinto** [comment] 2019-02-06 14:34
Please disregard the error. It also happens on a stack that does not use this plugin so it's not caused by it. Thanks.
