### ISSUE TITLE
Cannot read property 'serverSideEncryption' of undefined

### ISSUE THREAD

**Issue by skylarmb** [dougmoscrop/serverless-plugin-split-stacks#27] opened 2018-02-09 21:17 UTC
When upgrading to 1.4.0 we get this error. 1.3.2 is working for us in the meantime.

```
Serverless: Invoke aws:deploy:deploy
Serverless: Uploading CloudFormation file to S3...
Serverless: Uploading artifacts...
Serverless: Uploading service .zip file to S3 (50.2 MB)...
 
  Type Error ---------------------------------------------
 
  Cannot read property 'serverSideEncryption' of undefined
 
     For debugging logs, run again after setting the "SLS_DEBUG=*" environment variable.
 
  Stack Trace --------------------------------------------
 
TypeError: Cannot read property 'serverSideEncryption' of undefined
    at encryptionFields.reduce ([...]/node_modules/serverless-plugin-split-stacks/lib/utils.js:289:33)
    at Array.reduce (native)
    at ServerlessPluginSplitStacks.getEncryptionParams ([...]/node_modules/serverless-plugin-split-stacks/lib/utils.js:288:29)
    at Promise.all._.map.file ([...]/node_modules/serverless-plugin-split-stacks/split-stacks.js:92:43)
    at arrayMap ([...]/node_modules/lodash/lodash.js:631:23)
    at Function.map ([...]/node_modules/lodash/lodash.js:9546:14)
    at provider.getServerlessDeploymentBucketName.then.deploymentBucket ([...]/node_modules/serverless-plugin-split-stacks/split-stacks.js:83:30)
```

**Comment by dougmoscrop** [comment] 2018-02-09 21:23
Duplicate of https://github.com/dougmoscrop/serverless-plugin-split-stacks/issues/26

**Comment by skylarmb** [comment] 2018-02-09 21:23
oops! sorry about that

**Closed by dougmoscrop** 2018-02-09 21:23 UTC
