### ISSUE TITLE
APINestedStack Error

### ISSUE THREAD

**Issue by yogumanivannan** [dougmoscrop/serverless-plugin-split-stacks#21] opened 2017-12-08 03:55 UTC
An error occurred: APINestedStack - Template format error: Outputs count 62 is greater than max allowed 60.

I get this issue while using serverless deploy

**Comment by dougmoscrop** [comment] 2017-12-08 14:09
Yeah, this is another CloudFormation limit that this plugin does not have logic for trying to solve. It's basically a case of having to further divide in to even *more* nested stacks because of output/input limit, not just resource count. I can imagine how we might accomplish it, just not done.

**Comment by yogumanivannan** [comment] 2017-12-08 14:13
oops i was really hoping to have a solution... Is there any other alternatives left or should i architect my endpoints in a way that it doesn't affect resource count or size limit ?

**Comment by dougmoscrop** [comment] 2017-12-08 17:28
Do you have a lot of separate functions/endpoints? An alternative is to combine them together, and just have one, or maybe a few.

```yaml

functions:
  api:
    handler: api.js
    events:
      - http ANY /
      - http ANY /{any+}
```

or per some kind of logical thing

```yaml

functions:
  fooApi:
    handler: api.js
    events:
      - http ANY /foo
      - http ANY /foo/{any+}

functions:
  fooApi:
    handler: api.js
    events:
      - http ANY /bar
      - http ANY /bar/{any+}
```

But not "getFoo", "putFoo", "postFoo", etc.

You can see my module https://github.com/dougmoscrop/serverless-http which will let you use routing like Koa/Express to make the function handler code dead simple

**Comment by yogumanivannan** [comment] 2017-12-09 04:22
The problem is it is a existing application, so i cannot change as your suggestion now. Also all the request validations are handled in API Gateway request validator. I have also requested for limit increase with AWS support. Let me see how it goes

**Comment by brunocascio** [comment] 2018-02-02 17:13
Even combining events does not work :(

Any update on this?

**Comment by dougmoscrop** [comment] 2018-02-02 17:36
The easiest way for me to help is if you can share with me the actual CF templates so I don't have to guess about what is being exposed and make a focused suggestion/fix.  Obviously you should anonymize/sanitize anything in your examples.

**Comment by brunocascio** [comment] 2018-02-02 17:44
Now it's working, but I think that combine resource is just a patch. If you have a lot of endpoints the problem will appear again :/

**Comment by dougmoscrop** [comment] 2018-02-08 22:22
You're right, unfortunately this plugin will not by you an endless ramp, you still have to try to split up concerns in to separate services.

One way to help 'move the cliff', so to speak, would be to modify the sub-stack splitting logic located [here](https://github.com/dougmoscrop/serverless-plugin-split-stacks/blob/master/lib/utils.js#L142) to do something like:

```js
if (Object.keys(stack.Resources).length < 200 && Object.keys(stack.Outputs).length < 60) {
}
```

this would move some API resources to a new stack (APINestedStack2) but I am not sure if there would be other issues there. It's a game of cat and mouse.

**Comment by dougmoscrop** [comment] 2018-02-08 22:28
Sorry, this is a duplicate of https://github.com/dougmoscrop/serverless-plugin-split-stacks/issues/15

I will move my comment to there.

**Closed by dougmoscrop** 2018-02-08 22:28 UTC
